// Re-export shared protocol types for use throughout the client
export type {
  Profile,
  FixtureDef,
  FixtureParams,
  FixturePosition,
  ShowState,
  Preset,
  EffectTemplate,
  EffectInstance,
  Waveform,
  Cue,
  Cuelist,
  CuelistPlayback,
  FollowMode,
  SimpleTile,
  SimpleTileType,
  SimplePageConfig,
  ClientMessage,
  ServerMessage,
  SetFixtureMsg,
  MoveFixtureMsg,
  SetBlackoutMsg,
  DmxUpdateMsg,
  StateMsg,
  PatchUpdateMsg,
  PresetsUpdateMsg,
  EffectsUpdateMsg,
  CuelistsUpdateMsg,
  SimplePageUpdateMsg,
  FlashMsg,
  UpdateSimplePageMsg,
} from '@lites/shared';
